config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  devise_for :users
  resources :projects

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  # before_create :set_owner_id

  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users

  validates :title, presence: true

  # def set_owner_id
  #   self.owner_id = current_user.id
  # end

  def owner
    self.users.find(self.owner_id).name
  end

end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
	belongs_to :user
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :project_users
  has_many :projects, through: :project_users

  after_create :send_email

  validates :email, presence: true

  def send_email
    UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to projects_path
  	else
  		redirect_to new_user_session_path
  	end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
  	@projects = current_user.projects
  end

  def show
    redirect_to projects_path
  end

  def new
  	@project = Project.new
  end

  def create
  	@project = Project.new(project_params)
  	current_user.projects << @project
    @project.owner_id = current_user.id
  	if @project.save
      redirect_to projects_path
  	else
      render 'new'
  	end
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
  	params.require(:project).permit(:title, :content, :owner)
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
    
  end

  def edit

  end

  def update

  end

  def new

  end

  def create
    p 'hello'
    p ' -'*1230
  end

  def destroy

  end

  private

  def users_params
  	params.require(:user).permit(:name, :email, :user_type)
  end

  def set_user
  	@user = User.find(params: id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete  %><br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h3>Edit Project</h3>
<%= form_for @project do |f| %>
	Title: <%= f.text_field :title %><br><br>
  Content: <%= f.text_area :content %><br><br>
  <%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<%= link_to "New Project", new_project_path %><br>
<% @projects.each do |proj| %>
  <br>
  <div>
	  <b>title:</b> <%= proj.title %><br>
  </div>
  <b>content:</b> <%= proj.content %><br>
  <b>owner:</b> <%= User.find(proj.owner_id).name %><br>
  <%= link_to("Edit", edit_project_path(proj.id)) %>
  <%= link_to "Delete", project_path(proj.id) , method: :delete, data: {confirm: "Are  you sure?"} %><br>
  ------------------------------------------------------
<% end %>

app/views/projects/new.html.erb
<h3>Enter new Project</h3>
<%= form_for @project do |f| %>
	Title: <%= f.text_field :title %><br><br>
  Content: <%= f.text_area :content %><br><br>
  Owner: <%= 
  <%= f.submit %>
<% end %>